### ISSUE TITLE
Balance level 2 and 3

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#127]
After creating the cinema and the food court, these need to be balanced. It has to be in line with the level 1 balance (that still can be improved nonetheless) and include the correct people and numbers.

We need to decide which one to put as level 2 and level 3.

# Definition of done

- [x] The choice is done to understand which level will be level 2 and 3
- [ ] Levels are balanced with the right amount of characters and types
- [x] The tutorials are set correctly on each level
- [x] The levels are correctly set in the level selection

**Comment by theenergici** [comment]
For now the levels are set as Cinema = lvl 3, and food court =lvl 2

**Comment by theenergici** [comment]
# FoodCourt
- [ ] tutorials are set
- [ ] the amount of characters are set

**Comment by theenergici** [comment]
# Cinema
- [ ] tutorials are set
- [ ] the amount of characters are set
@iSergioMejia
