### ISSUE TITLE
Level has been reached logic and stars not working

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#141]
# Problem statement

The logic in the Level menu selection to check if a certain level, and the one in the Points Manager to save the level reached, is wrong and needs to be fixed.

**Comment by iSergioMejia** [comment]
Is being fixed directly in #133

**Comment by theenergici** [comment]
Can you be more specific in what is the issue? The level doesn't unlock correctly?

**Comment by iSergioMejia** [comment]
The level order was wrong since the scene index logic we were using was wrong (the same way we were comparing to sceneIndex-1, we needed to save sceneIndex-1 in the PlayerPrefs, not sceneIndex)
