### ISSUE TITLE
Block back parts of the level

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#26]
# Problem statement

Currently, we have floors in the back of the level that customers used to go up and down from the game, as well to spawn and despawn. This shouldn't be seen by the player so the current discussed solution is to add black objects that block it.

# Definition of Done

- Back parts of levels are no longer visible to the player
- This should be toggable in Unity for debug purposes

**Comment by theenergici** [comment]
Done in [issue 22](https://github.com/GOUStudios/COVerIt-/issues/22)
