### ISSUE TITLE
Integrate UI with managers

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#29]
# Problem statements

In past sprint the UI for the level was created in #18 so now we need to integrate it with the managers that have the state for each component.

# Definition of Done

- Time remaining shown on screen
- Boss anger shown on screen
- Taser energy shown on screen

**Comment by theenergici** [comment]
this part was done in  [issue 22](https://github.com/GOUStudios/COVerIt-/issues/22)
the `points manager` + `starts` and `points` integration shall be done after [issue 30](https://github.com/GOUStudios/COVerIt-/issues/30) is done.
but those are not requested in this issue.
