### ISSUE TITLE
Points bar is not working

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#57]
# Problem statement

Currently the points bar is not working, always showing 0%

# Steps to reproduce

- Open Level1 scene
- Start playing the game hitting people
- The bar won't increase and in the Console logs it will always show the log "points perc0".

# Definition of done

The bar should increase when hitting correctly people, filling itself.

**Comment by vincenzocas** [comment]
It is not a problem of the points bar, it is caused by the function getInitialMaxPoints() in level setting manager (I don't know who have done it), everytime it returns the value 0, and this make the percentage equal to 0, but the UI bar works in the right way.

**Comment by iSergioMejia** [comment]
Waiting for #53 to be merged to see if this solves the issue
