### ISSUE TITLE
Integrate level loading with level transition

### ISSUE THREAD

**Issue by theenergici** [GOUStudios/COVerIt-#59]
# Problem statement

the level loading right now gives a signal to start the timer after a set amount of time to allow the NPCs to populate the scene. The transition screen should remain "black" until this timer starts, after which the level can start. 

# TODOs:

- [x] integrate level with level transition logically
- [ ] Block inputs until level starts
- [ ] run tests

**Comment by iSergioMejia** [comment]
Closed by #56
