### ISSUE TITLE
Make taser event to teach player how to use

### ISSUE THREAD

**Issue by iSergioMejia** [GOUStudios/COVerIt-#96]
# Problem statement

Level 2 or 3 will introduce the taser, so we have to implement the "enabled/disabled" feature on it so we can disable it on the first level. Moreover, we have to teach the user how to use it useing the events defined in #65 

# Definition of done

- Taser can be enabled/disabled, so the UI will disappear and right-clicking won't do anything.
- At the start of the level where it will be introduced, a popup shall appear hinting how to use it.

**Comment by theenergici** [comment]
@iSergioMejia in what level do you want it? also any specific trigger? or do we make it time based?

**Comment by theenergici** [comment]
@iSergioMejia if you want the taser event is done. you can do the text if you want. tbh i wasnt sure how to write it. maybe adding an image of a mouse highlighting the button could be a good idea.

**Comment by iSergioMejia** [comment]
Level 2, and the mouse symbol with the right click is perfect. The text could be like "We have provided you with a taser to help you in your duties. Activate it with right click, but use it wisely, as with a great power comes a great responsibility"

**Comment by theenergici** [comment]
added the tutorial for the taser on the food court level
If we want to add the mouse image we can do it later
